[package]
name = "p1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syscalls = "0.6.9"
sysinfo = "0.28.4"
gtk4 = "0.6.4"
glib = "0.17.5"
gio = "0.17.4"